$file = "c:\Users\adm-kh\source\repos\EZKPM\EZKPM.Client.Desktop\Views\AssetEditorWindow.axaml"
$content = Get-Content $file -Raw

$content = $content -replace 'Text="Asset Details"', 'Text="Eintrags-Details"'
$content = $content -replace 'ToolTip\.Tip="Pop Out Editor"', 'ToolTip.Tip="In eigenem Fenster öffnen"'
$content = $content -replace 'ToolTip\.Tip="Duplicate Asset"', 'ToolTip.Tip="Eintrag duplizieren"'
$content = $content -replace 'ToolTip\.Tip="Save and New"', 'ToolTip.Tip="Speichern &amp; Neu"'
$content = $content -replace 'ToolTip\.Tip="Save and Close"', 'ToolTip.Tip="Speichern &amp; Schließen"'
$content = $content -replace 'Text="Title"', 'Text="Titel"'
$content = $content -replace 'PlaceholderText="e\.g\. My Bank Account"', 'PlaceholderText="z.B. Mein Bankkonto"'
$content = $content -replace 'Text="Asset Type"', 'Text="Eintragstyp"'
$content = $content -replace 'Text="Parent Folder"', 'Text="Übergeordneter Ordner"'
$content = $content -replace 'Text="Username / Email"', 'Text="Benutzername / E-Mail"'
$content = $content -replace 'ToolTip\.Tip="Copy"', 'ToolTip.Tip="Kopieren"'
$content = $content -replace 'Text="Password"', 'Text="Passwort"'
$content = $content -replace 'ToolTip\.Tip="Generate"', 'ToolTip.Tip="Generieren"'
$content = $content -replace 'Content="Show Password"', 'Content="Passwort anzeigen"'
$content = $content -replace 'Text="Payment Method"', 'Text="Zahlungsmethode"'
$content = $content -replace '>Credit / Debit Card<', '>Kredit- / Debitkarte<'
$content = $content -replace '>Payment Service \(e\.g\. PayPal\)<', '>Zahlungsdienstleister (z.B. PayPal)<'
$content = $content -replace 'Text="Card Holder / Account Name"', 'Text="Karteninhaber / Kontoname"'
$content = $content -replace 'Text="Expiry \(MM/YY\)"', 'Text="Ablaufdatum (MM/JJ)"'
$content = $content -replace 'Text="CVC / PIN"', 'Text="Prüfziffer / PIN"'
$content = $content -replace 'Text="Primary File \(Certificate / Key / Container\)"', 'Text="Hauptdatei (Zertifikat / Schlüssel / Container)"'
$content = $content -replace 'PlaceholderText="No file selected\.\.\."', 'PlaceholderText="Keine Datei ausgewählt..."'
$content = $content -replace 'ToolTip\.Tip="Browse\.\.\."', 'ToolTip.Tip="Durchsuchen..."'
$content = $content -replace 'ToolTip\.Tip="Clear"', 'ToolTip.Tip="Leeren"'
$content = $content -replace 'ToolTip\.Tip="Download"', 'ToolTip.Tip="Herunterladen"'
$content = $content -replace 'Text="Secondary File \(e\.g\. Public Key / Cert\)"', 'Text="Zweitdatei (z.B. Public Key / Zertifikat)"'
$content = $content -replace 'Header="Password Generator Settings"', 'Header="Passwort-Generator Einstellungen"'
$content = $content -replace 'Text="Length"', 'Text="Länge"'
$content = $content -replace 'Content="Uppercase \(A-Z\)"', 'Content="Großbuchstaben (A-Z)"'
$content = $content -replace 'Content="Lowercase \(a-z\)"', 'Content="Kleinbuchstaben (a-z)"'
$content = $content -replace 'Content="Numbers \(0-9\)"', 'Content="Zahlen (0-9)"'
$content = $content -replace 'Content="Symbols \(\!@#\$\)"', 'Content="Sonderzeichen (!@#$)"'
$content = $content -replace 'Text="TOTP Secret Key \(Base32\)"', 'Text="TOTP Geheimnis (Base32)"'
$content = $content -replace 'Content="Show Secret"', 'Content="Geheimnis anzeigen"'
$content = $content -replace 'Text="Current Code:"', 'Text="Aktueller Code:"'
$content = $content -replace 'Header="General &amp;amp; Notes"', 'Header="Allgemein &amp;amp; Notizen"'
$content = $content -replace 'Text="Secure Notes"', 'Text="Sichere Notizen"'
$content = $content -replace 'PlaceholderText="Additional information\.\.\."', 'PlaceholderText="Zusätzliche Informationen..."'
$content = $content -replace 'Text="Detailed Description"', 'Text="Ausführliche Beschreibung"'
$content = $content -replace 'Header="Custom Variables"', 'Header="Zusatzfelder"'
$content = $content -replace 'PlaceholderText="\(User Prompt\)"', 'PlaceholderText="(Wird beim Nutzer abgefragt)"'
$content = $content -replace 'ToolTip\.Tip="Add Variable"', 'ToolTip.Tip="Variable hinzufügen"'
$content = $content -replace 'Header="Permissions \(ACL\)"', 'Header="Berechtigungen (ACL)"'
$content = $content -replace 'Content="Deny \(-1\)"', 'Content="Verweigern (-1)"'
$content = $content -replace 'Content="Execute \(1\)"', 'Content="Ausführen (1)"'
$content = $content -replace 'Content="Read \(2\)"', 'Content="Lesen (2)"'
$content = $content -replace 'Content="Owner \(3\)"', 'Content="Besitzer (3)"'
$content = $content -replace 'Header="Attachments"', 'Header="Dateianhänge"'
$content = $content -replace 'ToolTip\.Tip="Add File\(s\)\.\.\."', 'ToolTip.Tip="Datei(en) hinzufügen..."'
$content = $content -replace 'ToolTip\.Tip="Download Selected"', 'ToolTip.Tip="Auswahl herunterladen"'
$content = $content -replace 'ToolTip\.Tip="Remove Selected"', 'ToolTip.Tip="Auswahl entfernen"'
$content = $content -replace 'Header="Settings &amp;amp; Expiry"', 'Header="Einstellungen &amp;amp; Ablaufdatum"'
$content = $content -replace 'Text="Password Validity \(Days, max 365\)"', 'Text="Passwort-Gültigkeit (Tage, max 365)"'
$content = $content -replace 'Header="Login Automation Settings \(Browser Extension\)"', 'Header="Login Automatisierung (Browser Extension)"'
$content = $content -replace 'Text="Login Method"', 'Text="Anmelde-Methode"'
$content = $content -replace 'Content="Enable AutoLearn Mode \(Observe DOM\)"', 'Content="AutoLearn Modus aktivieren (DOM beobachten)"'
$content = $content -replace 'Text="Learned DOM Selectors"', 'Text="Gelernte DOM-Selektoren"'

Set-Content -Path $file -Value $content -NoNewline
