// <auto-generated />
using System;
using EZKPM.Server.PDP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EZKPM.Server.PDP.Migrations
{
    [DbContext(typeof(EzkpmDbContext))]
    [Migration("20260506123245_AddUpdatedUtcToVaultAsset")]
    partial class AddUpdatedUtcToVaultAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AssetAcl", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdSid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedKeyShare")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "AdSid");

                    b.ToTable("AssetAcls");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CurrentEntryHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedLogBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PreviousEntryHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PreviousEntryHash")
                        .IsUnique();

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.UserProfile", b =>
                {
                    b.Property<string>("AdSid")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedMasterKeyBackup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdSid");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CipherBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetadataHash");

                    b.ToTable("VaultAssets");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultRecoveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EphemeralUserPubKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredShares")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VaultRecoveryRequests");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultRecoveryShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedShareBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecoveryRequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryRequestId");

                    b.ToTable("VaultRecoveryShares");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AssetAcl", b =>
                {
                    b.HasOne("EZKPM.Server.PDP.Data.VaultAsset", "Asset")
                        .WithMany("Acls")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AuditLog", b =>
                {
                    b.HasOne("EZKPM.Server.PDP.Data.VaultAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultRecoveryShare", b =>
                {
                    b.HasOne("EZKPM.Server.PDP.Data.VaultRecoveryRequest", null)
                        .WithMany("ProvidedShares")
                        .HasForeignKey("RecoveryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultAsset", b =>
                {
                    b.Navigation("Acls");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultRecoveryRequest", b =>
                {
                    b.Navigation("ProvidedShares");
                });
#pragma warning restore 612, 618
        }
    }
}
