// <auto-generated />
using System;
using EZKPM.Server.PDP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EZKPM.Server.PDP.Migrations
{
    [DbContext(typeof(EzkpmDbContext))]
    partial class EzkpmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AssetAcl", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdSid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedKeyShare")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "AdSid");

                    b.ToTable("AssetAcls");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CurrentEntryHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedLogBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PreviousEntryHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PreviousEntryHash")
                        .IsUnique();

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CipherBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("MetadataHash");

                    b.ToTable("VaultAssets");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AssetAcl", b =>
                {
                    b.HasOne("EZKPM.Server.PDP.Data.VaultAsset", "Asset")
                        .WithMany("Acls")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.AuditLog", b =>
                {
                    b.HasOne("EZKPM.Server.PDP.Data.VaultAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("EZKPM.Server.PDP.Data.VaultAsset", b =>
                {
                    b.Navigation("Acls");
                });
#pragma warning restore 612, 618
        }
    }
}
