//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZKPM.Client.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZKPM.Client.Desktop.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount (e.g. 49.99 USD) ähnelt.
        /// </summary>
        public static string AuditDialog_AmountWatermark {
            get {
                return ResourceManager.GetString("AuditDialog_AmountWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorize &amp; Log ähnelt.
        /// </summary>
        public static string AuditDialog_BtnAuthorize {
            get {
                return ResourceManager.GetString("AuditDialog_BtnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Access ähnelt.
        /// </summary>
        public static string AuditDialog_BtnCancel {
            get {
                return ResourceManager.GetString("AuditDialog_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The browser is requesting payment credentials. Enterprise policy requires a tamper-proof audit log of the amount and reference before autofill is authorized. ähnelt.
        /// </summary>
        public static string AuditDialog_Description {
            get {
                return ResourceManager.GetString("AuditDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠️ Payment Authorization (FA 22) ähnelt.
        /// </summary>
        public static string AuditDialog_Header {
            get {
                return ResourceManager.GetString("AuditDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order ID / Reference ähnelt.
        /// </summary>
        public static string AuditDialog_OrderIdWatermark {
            get {
                return ResourceManager.GetString("AuditDialog_OrderIdWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EZK-PM Security Audit ähnelt.
        /// </summary>
        public static string AuditDialog_Title {
            get {
                return ResourceManager.GetString("AuditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always Allow ähnelt.
        /// </summary>
        public static string LocalApp_AllowAlways {
            get {
                return ResourceManager.GetString("LocalApp_AllowAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Once ähnelt.
        /// </summary>
        public static string LocalApp_AllowOnce {
            get {
                return ResourceManager.GetString("LocalApp_AllowOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Access ähnelt.
        /// </summary>
        public static string LocalApp_Deny {
            get {
                return ResourceManager.GetString("LocalApp_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠️ Local Application Access ähnelt.
        /// </summary>
        public static string LocalApp_Header {
            get {
                return ResourceManager.GetString("LocalApp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local App Authorization ähnelt.
        /// </summary>
        public static string LocalApp_Title {
            get {
                return ResourceManager.GetString("LocalApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp; Restart ähnelt.
        /// </summary>
        public static string ServerConfig_BtnSave {
            get {
                return ResourceManager.GetString("ServerConfig_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the URL of your Ironclad Vault Server. ähnelt.
        /// </summary>
        public static string ServerConfig_Desc {
            get {
                return ResourceManager.GetString("ServerConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Configuration ähnelt.
        /// </summary>
        public static string ServerConfig_Title {
            get {
                return ResourceManager.GetString("ServerConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server URL (e.g. https://vault.mycompany.com) ähnelt.
        /// </summary>
        public static string ServerConfig_UrlWatermark {
            get {
                return ResourceManager.GetString("ServerConfig_UrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application: {0} ähnelt.
        /// </summary>
        public static string SsoDialog_AppId {
            get {
                return ResourceManager.GetString("SsoDialog_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✅ Approve ähnelt.
        /// </summary>
        public static string SsoDialog_Approve {
            get {
                return ResourceManager.GetString("SsoDialog_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ Deny ähnelt.
        /// </summary>
        public static string SsoDialog_Deny {
            get {
                return ResourceManager.GetString("SsoDialog_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An application is requesting to login via your Ironclad Vault account. ähnelt.
        /// </summary>
        public static string SsoDialog_Desc1 {
            get {
                return ResourceManager.GetString("SsoDialog_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to approve this login? ähnelt.
        /// </summary>
        public static string SsoDialog_Desc2 {
            get {
                return ResourceManager.GetString("SsoDialog_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🚨 Web-SSO Login Attempt Detected! ähnelt.
        /// </summary>
        public static string SsoDialog_Header {
            get {
                return ResourceManager.GetString("SsoDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server: {0} ähnelt.
        /// </summary>
        public static string SsoDialog_Server {
            get {
                return ResourceManager.GetString("SsoDialog_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ironclad Vault - SSO Login Request ähnelt.
        /// </summary>
        public static string SsoDialog_Title {
            get {
                return ResourceManager.GetString("SsoDialog_Title", resourceCulture);
            }
        }
    }
}
