//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZKPM.Client.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZKPM.Client.Desktop.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User / SID ähnelt.
        /// </summary>
        public static string asset {
            get {
                return ResourceManager.GetString("asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Propagate access rights (ACL) to all child assets (Overwrites existing rights) ähnelt.
        /// </summary>
        public static string AssetEditor_AclApplyChildren {
            get {
                return ResourceManager.GetString("AssetEditor_AclApplyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage users who have access to this asset/folder. ähnelt.
        /// </summary>
        public static string AssetEditor_AclDesc {
            get {
                return ResourceManager.GetString("AssetEditor_AclDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable inheritance from parent folder ähnelt.
        /// </summary>
        public static string AssetEditor_AclInherit {
            get {
                return ResourceManager.GetString("AssetEditor_AclInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Access (0) ähnelt.
        /// </summary>
        public static string AssetEditor_AclNone {
            get {
                return ResourceManager.GetString("AssetEditor_AclNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string AssetEditor_ColDesc {
            get {
                return ResourceManager.GetString("AssetEditor_ColDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string AssetEditor_ColName {
            get {
                return ResourceManager.GetString("AssetEditor_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role / Rights ähnelt.
        /// </summary>
        public static string AssetEditor_ColRole {
            get {
                return ResourceManager.GetString("AssetEditor_ColRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User / Group ähnelt.
        /// </summary>
        public static string AssetEditor_ColUser {
            get {
                return ResourceManager.GetString("AssetEditor_ColUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string AssetEditor_ColValue {
            get {
                return ResourceManager.GetString("AssetEditor_ColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify variables for website automation. If the value is empty, you will be prompted when used. ähnelt.
        /// </summary>
        public static string AssetEditor_CustomVarsDesc {
            get {
                return ResourceManager.GetString("AssetEditor_CustomVarsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailed description... ähnelt.
        /// </summary>
        public static string AssetEditor_DescWatermark {
            get {
                return ResourceManager.GetString("AssetEditor_DescWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The validity period (max 365 days) has been exceeded. Please update the password immediately and save to restore access (e.g. Autofill). ähnelt.
        /// </summary>
        public static string AssetEditor_ExpiredWarningDesc {
            get {
                return ResourceManager.GetString("AssetEditor_ExpiredWarningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING: This asset has expired! ähnelt.
        /// </summary>
        public static string AssetEditor_ExpiredWarningTitle {
            get {
                return ResourceManager.GetString("AssetEditor_ExpiredWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Inherited] ähnelt.
        /// </summary>
        public static string AssetEditor_Inherited {
            get {
                return ResourceManager.GetString("AssetEditor_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount (e.g. 49.99 USD) ähnelt.
        /// </summary>
        public static string AuditDialog_AmountWatermark {
            get {
                return ResourceManager.GetString("AuditDialog_AmountWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorize &amp; Log ähnelt.
        /// </summary>
        public static string AuditDialog_BtnAuthorize {
            get {
                return ResourceManager.GetString("AuditDialog_BtnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Access ähnelt.
        /// </summary>
        public static string AuditDialog_BtnCancel {
            get {
                return ResourceManager.GetString("AuditDialog_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The browser is requesting payment credentials. Enterprise policy requires a tamper-proof audit log of the amount and reference before autofill is authorized. ähnelt.
        /// </summary>
        public static string AuditDialog_Description {
            get {
                return ResourceManager.GetString("AuditDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠️ Payment Authorization (FA 22) ähnelt.
        /// </summary>
        public static string AuditDialog_Header {
            get {
                return ResourceManager.GetString("AuditDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order ID / Reference ähnelt.
        /// </summary>
        public static string AuditDialog_OrderIdWatermark {
            get {
                return ResourceManager.GetString("AuditDialog_OrderIdWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EZK-PM Security Audit ähnelt.
        /// </summary>
        public static string AuditDialog_Title {
            get {
                return ResourceManager.GetString("AuditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string ConfirmDialog_BtnNo {
            get {
                return ResourceManager.GetString("ConfirmDialog_BtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string ConfirmDialog_BtnYes {
            get {
                return ResourceManager.GetString("ConfirmDialog_BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmation ähnelt.
        /// </summary>
        public static string ConfirmDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CsvMapping_BtnCancel {
            get {
                return ResourceManager.GetString("CsvMapping_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string CsvMapping_BtnImport {
            get {
                return ResourceManager.GetString("CsvMapping_BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please map the columns of your CSV file to the EZKPM fields: ähnelt.
        /// </summary>
        public static string CsvMapping_Desc {
            get {
                return ResourceManager.GetString("CsvMapping_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Import Mapping ähnelt.
        /// </summary>
        public static string CsvMapping_Header {
            get {
                return ResourceManager.GetString("CsvMapping_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name / Title: ähnelt.
        /// </summary>
        public static string CsvMapping_LblName {
            get {
                return ResourceManager.GetString("CsvMapping_LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes: ähnelt.
        /// </summary>
        public static string CsvMapping_LblNotes {
            get {
                return ResourceManager.GetString("CsvMapping_LblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        public static string CsvMapping_LblPass {
            get {
                return ResourceManager.GetString("CsvMapping_LblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website / URL: ähnelt.
        /// </summary>
        public static string CsvMapping_LblUrl {
            get {
                return ResourceManager.GetString("CsvMapping_LblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username: ähnelt.
        /// </summary>
        public static string CsvMapping_LblUser {
            get {
                return ResourceManager.GetString("CsvMapping_LblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Column Mapping ähnelt.
        /// </summary>
        public static string CsvMapping_Title {
            get {
                return ResourceManager.GetString("CsvMapping_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always Allow ähnelt.
        /// </summary>
        public static string LocalApp_AllowAlways {
            get {
                return ResourceManager.GetString("LocalApp_AllowAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Once ähnelt.
        /// </summary>
        public static string LocalApp_AllowOnce {
            get {
                return ResourceManager.GetString("LocalApp_AllowOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Access ähnelt.
        /// </summary>
        public static string LocalApp_Deny {
            get {
                return ResourceManager.GetString("LocalApp_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠️ Local Application Access ähnelt.
        /// </summary>
        public static string LocalApp_Header {
            get {
                return ResourceManager.GetString("LocalApp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local App Authorization ähnelt.
        /// </summary>
        public static string LocalApp_Title {
            get {
                return ResourceManager.GetString("LocalApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🗑️ Clean Up ähnelt.
        /// </summary>
        public static string Main_BtnClean {
            get {
                return ResourceManager.GetString("Main_BtnClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permanently deletes all orphaned assets ähnelt.
        /// </summary>
        public static string Main_BtnCleanTooltip {
            get {
                return ResourceManager.GetString("Main_BtnCleanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🗑️ Delete ähnelt.
        /// </summary>
        public static string Main_BtnDelete {
            get {
                return ResourceManager.GetString("Main_BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 📥 Import ähnelt.
        /// </summary>
        public static string Main_BtnImport {
            get {
                return ResourceManager.GetString("Main_BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + Asset ähnelt.
        /// </summary>
        public static string Main_BtnNewAsset {
            get {
                return ResourceManager.GetString("Main_BtnNewAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + Folder ähnelt.
        /// </summary>
        public static string Main_BtnNewFolder {
            get {
                return ResourceManager.GetString("Main_BtnNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🔄 Restore ähnelt.
        /// </summary>
        public static string Main_BtnRestore {
            get {
                return ResourceManager.GetString("Main_BtnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Main_ColDesc {
            get {
                return ResourceManager.GetString("Main_ColDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Main_ColName {
            get {
                return ResourceManager.GetString("Main_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string Main_ColPath {
            get {
                return ResourceManager.GetString("Main_ColPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string Main_ColType {
            get {
                return ResourceManager.GetString("Main_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Types ähnelt.
        /// </summary>
        public static string Main_FilterAll {
            get {
                return ResourceManager.GetString("Main_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expired (Rotation) ähnelt.
        /// </summary>
        public static string Main_FilterExpired {
            get {
                return ResourceManager.GetString("Main_FilterExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recycle Bin ähnelt.
        /// </summary>
        public static string Main_FilterTrash {
            get {
                return ResourceManager.GetString("Main_FilterTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPIRED ähnelt.
        /// </summary>
        public static string Main_LblExpired {
            get {
                return ResourceManager.GetString("Main_LblExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Folder ähnelt.
        /// </summary>
        public static string Main_MenuDeleteFolder {
            get {
                return ResourceManager.GetString("Main_MenuDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Folder ähnelt.
        /// </summary>
        public static string Main_MenuEditFolder {
            get {
                return ResourceManager.GetString("Main_MenuEditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings &amp; Change Server ähnelt.
        /// </summary>
        public static string Main_MenuSettings {
            get {
                return ResourceManager.GetString("Main_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Private ähnelt.
        /// </summary>
        public static string Main_PrivateFolder {
            get {
                return ResourceManager.GetString("Main_PrivateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search... ähnelt.
        /// </summary>
        public static string Main_SearchWatermark {
            get {
                return ResourceManager.GetString("Main_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🗂️ Assets ähnelt.
        /// </summary>
        public static string Main_TabAssets {
            get {
                return ResourceManager.GetString("Main_TabAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string PwdPrompt_BtnCancel {
            get {
                return ResourceManager.GetString("PwdPrompt_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string PwdPrompt_BtnOk {
            get {
                return ResourceManager.GetString("PwdPrompt_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Key File ähnelt.
        /// </summary>
        public static string PwdPrompt_BtnSelectKey {
            get {
                return ResourceManager.GetString("PwdPrompt_BtnSelectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the Master Password and/or select a Key File for the KeePass database: ähnelt.
        /// </summary>
        public static string PwdPrompt_Desc {
            get {
                return ResourceManager.GetString("PwdPrompt_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file selected ähnelt.
        /// </summary>
        public static string PwdPrompt_NoFile {
            get {
                return ResourceManager.GetString("PwdPrompt_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password / Key File Required ähnelt.
        /// </summary>
        public static string PwdPrompt_Title {
            get {
                return ResourceManager.GetString("PwdPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master Password ähnelt.
        /// </summary>
        public static string PwdPrompt_Watermark {
            get {
                return ResourceManager.GetString("PwdPrompt_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch automatically in background at Windows startup (System Tray) ähnelt.
        /// </summary>
        public static string ServerConfig_AutoStart {
            get {
                return ResourceManager.GetString("ServerConfig_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ServerConfig_BtnCancel {
            get {
                return ResourceManager.GetString("ServerConfig_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save &amp; Restart ähnelt.
        /// </summary>
        public static string ServerConfig_BtnSave {
            get {
                return ResourceManager.GetString("ServerConfig_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the URL of your Ironclad Vault Server. ähnelt.
        /// </summary>
        public static string ServerConfig_Desc {
            get {
                return ResourceManager.GetString("ServerConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup Server Connection ähnelt.
        /// </summary>
        public static string ServerConfig_Header {
            get {
                return ResourceManager.GetString("ServerConfig_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Configuration ähnelt.
        /// </summary>
        public static string ServerConfig_Title {
            get {
                return ResourceManager.GetString("ServerConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server URL (e.g. https://vault.mycompany.com) ähnelt.
        /// </summary>
        public static string ServerConfig_UrlWatermark {
            get {
                return ResourceManager.GetString("ServerConfig_UrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application: {0} ähnelt.
        /// </summary>
        public static string SsoDialog_AppId {
            get {
                return ResourceManager.GetString("SsoDialog_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✅ Approve ähnelt.
        /// </summary>
        public static string SsoDialog_Approve {
            get {
                return ResourceManager.GetString("SsoDialog_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ Deny ähnelt.
        /// </summary>
        public static string SsoDialog_Deny {
            get {
                return ResourceManager.GetString("SsoDialog_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An application is requesting to login via your Ironclad Vault account. ähnelt.
        /// </summary>
        public static string SsoDialog_Desc1 {
            get {
                return ResourceManager.GetString("SsoDialog_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to approve this login? ähnelt.
        /// </summary>
        public static string SsoDialog_Desc2 {
            get {
                return ResourceManager.GetString("SsoDialog_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🚨 Web-SSO Login Attempt Detected! ähnelt.
        /// </summary>
        public static string SsoDialog_Header {
            get {
                return ResourceManager.GetString("SsoDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server: {0} ähnelt.
        /// </summary>
        public static string SsoDialog_Server {
            get {
                return ResourceManager.GetString("SsoDialog_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ironclad Vault - SSO Login Request ähnelt.
        /// </summary>
        public static string SsoDialog_Title {
            get {
                return ResourceManager.GetString("SsoDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows authentication canceled. ähnelt.
        /// </summary>
        public static string Startup_AuthCanceled {
            get {
                return ResourceManager.GetString("Startup_AuthCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new vault ähnelt.
        /// </summary>
        public static string Startup_BtnCreateVault {
            get {
                return ResourceManager.GetString("Startup_BtnCreateVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Migrate password &amp; Unlock ähnelt.
        /// </summary>
        public static string Startup_BtnMigrate {
            get {
                return ResourceManager.GetString("Startup_BtnMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request 4-Eyes Recovery ähnelt.
        /// </summary>
        public static string Startup_BtnRecovery {
            get {
                return ResourceManager.GetString("Startup_BtnRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pair device ähnelt.
        /// </summary>
        public static string Startup_BtnSetupDevice {
            get {
                return ResourceManager.GetString("Startup_BtnSetupDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock with Windows Credentials ähnelt.
        /// </summary>
        public static string Startup_BtnUnlock {
            get {
                return ResourceManager.GetString("Startup_BtnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical System Error: {0} ähnelt.
        /// </summary>
        public static string Startup_CriticalError {
            get {
                return ResourceManager.GetString("Startup_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrypting Seamless SSO via DPAPI... ähnelt.
        /// </summary>
        public static string Startup_DecryptingSso {
            get {
                return ResourceManager.GetString("Startup_DecryptingSso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device not paired. ähnelt.
        /// </summary>
        public static string Startup_DeviceNotPaired {
            get {
                return ResourceManager.GetString("Startup_DeviceNotPaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a URL. ähnelt.
        /// </summary>
        public static string Startup_ErrNoUrl {
            get {
                return ResourceManager.GetString("Startup_ErrNoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        public static string Startup_Error {
            get {
                return ResourceManager.GetString("Startup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server unreachable. Please check the URL. ähnelt.
        /// </summary>
        public static string Startup_ErrServerUnreachable {
            get {
                return ResourceManager.GetString("Startup_ErrServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your old Master Password to safely migrate it to the new DPAPI system: ähnelt.
        /// </summary>
        public static string Startup_MigrateDesc {
            get {
                return ResourceManager.GetString("Startup_MigrateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Migration to Seamless SSO ähnelt.
        /// </summary>
        public static string Startup_MigrateTitle {
            get {
                return ResourceManager.GetString("Startup_MigrateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup new device ähnelt.
        /// </summary>
        public static string Startup_NewDevice {
            get {
                return ResourceManager.GetString("Startup_NewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠️ DPAPI Error: Windows password may have been reset. ähnelt.
        /// </summary>
        public static string Startup_RecoveryError {
            get {
                return ResourceManager.GetString("Startup_RecoveryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IMPORTANT! Your Recovery Key:
        ///{0}
        ///Please write it down! Login in 8s... ähnelt.
        /// </summary>
        public static string Startup_RecoveryKey {
            get {
                return ResourceManager.GetString("Startup_RecoveryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery requested. Generating temporary key pair... ähnelt.
        /// </summary>
        public static string Startup_RecoveryRequested {
            get {
                return ResourceManager.GetString("Startup_RecoveryRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery successful! Restoring Master Key... ähnelt.
        /// </summary>
        public static string Startup_RecoverySuccess {
            get {
                return ResourceManager.GetString("Startup_RecoverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for admin approvals (Shamir&apos;s Secret Sharing)... ähnelt.
        /// </summary>
        public static string Startup_RecoveryWaitAdmin {
            get {
                return ResourceManager.GetString("Startup_RecoveryWaitAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your 34-character Secret Key: ähnelt.
        /// </summary>
        public static string Startup_SecretKeyDesc {
            get {
                return ResourceManager.GetString("Startup_SecretKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security Lock: Please confirm with Windows Credentials (app start delayed). ähnelt.
        /// </summary>
        public static string Startup_SecurityLock {
            get {
                return ResourceManager.GetString("Startup_SecurityLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrypting Vault... ähnelt.
        /// </summary>
        public static string Startup_SplashDecr {
            get {
                return ResourceManager.GetString("Startup_SplashDecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting to Vault Server... ähnelt.
        /// </summary>
        public static string Startup_StatusConnect {
            get {
                return ResourceManager.GetString("Startup_StatusConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrypting Asset {0} of {1}... ähnelt.
        /// </summary>
        public static string Startup_StatusDecryptAsset {
            get {
                return ResourceManager.GetString("Startup_StatusDecryptAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Desktop Client... ähnelt.
        /// </summary>
        public static string Startup_StatusStartClient {
            get {
                return ResourceManager.GetString("Startup_StatusStartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EZKPM Startup ähnelt.
        /// </summary>
        public static string Startup_Title {
            get {
                return ResourceManager.GetString("Startup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock securely via Windows Profile (Seamless SSO). ähnelt.
        /// </summary>
        public static string Startup_UnlockDesc {
            get {
                return ResourceManager.GetString("Startup_UnlockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vault is locked. ähnelt.
        /// </summary>
        public static string Startup_VaultLocked {
            get {
                return ResourceManager.GetString("Startup_VaultLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong old password! ähnelt.
        /// </summary>
        public static string Startup_WrongLegacyPwd {
            get {
                return ResourceManager.GetString("Startup_WrongLegacyPwd", resourceCulture);
            }
        }
    }
}
